### ISSUE TITLE
HELP IT WONT OWRK!1!

### ISSUE THREAD

**Issue by Fish-Sticks** [prismatica-dev/OpenVapour#4]
Hello chat! Today I will be talking about one of my favorite topics.

I.. **LOVE** *c# floss software*

It's like OMG flossing and.. C#? That's so SKIBIDI

This is such an epic frotnite repository i fucking love flossing with C# AND vapor with u.
I'm so SO OPEN to talking about ur project on DISCORD (or reddit).

**Comment by prismatica-dev** [comment]
This issue will be deleted as it failed to contain the following KEYWORDS: rizz, sigma, ohio, gyatt, zooxanthellae, david
Additionally it needs to include today's "fun phrase": fungal infection

Furthermore, it would appear you are using some sort of fake language, "vapor" should be "vapour".

After you have corrected these issues, please click the "delete my account" button to receive the fastest support!
